[project]
name = "guitaroids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Christopher Chaar", email = "chaar0123@outlook.com" }]
requires-python = ">=3.12"
dependencies = [
  "attrs==26.1.0",
  "cffi==2.1.1",
  "iniconfig==2.3.0",
  "numpy==2.2.6",
  "packaging==26.3",
  "pluggy==1.6.0",
  "pycparser==3.0",
  "pygments==2.21.0",
  "pyguitarpro==0.11",
  "pyside6==6.11.2",
  "pyside6-addons==6.11.2",
  "pyside6-essentials==6.11.2",
  "pytest==9.1.1",
  "shiboken6==6.11.2",
  "sounddevice==0.5.6",
  "soundfile==0.14.0",
  "tinysoundfont==0.3.7",
  "typing-extensions==4.16.0",
]

[project.scripts]
guitaroids = "guitaroids.__main__:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."
